# Generated by Django 5.2.4 on 2025-07-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_workorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Check if this company is a client (a managed building)'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_property_manager',
            field=models.BooleanField(default=False, help_text='Check if this company is a PM agency'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text='Check if this company is a contractor'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='Select the Property Manager Agency that manages this client site.', limit_choices_to={'company_type': 'pm_agency'}, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
