# Generated by Django 5.2.4 on 2025-07-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businesstype_remove_workorder_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('duplex', 'Duplex'), ('house', 'House'), ('commercial', 'Commercial Unit')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_property_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.client'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_apartments', models.PositiveIntegerField(default=0)),
                ('num_duplexes', models.PositiveIntegerField(default=0)),
                ('num_houses', models.PositiveIntegerField(default=0)),
                ('num_commercial_units', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_groups', to='core.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unitgroup'),
        ),
    ]
