# Generated by Django 5.2.4 on 2025-07-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unit_city_unit_county_unit_eircode_unit_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.businesstype'),
        ),
    ]
