# Generated by Django 5.2.4 on 2025-08-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company_contact_email_company_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_common_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.unit'),
        ),
    ]
